# Generated by Django 3.1.4 on 2020-12-15 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtubeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'video')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'video')},
        ),
    ]
